<h1>PyCitySchools</h1>


# Table of contents
1. Introduction<br>
2. Import libraries
3. District Summary
4. School Summary
6. Top Performing Schools (By Passing Rate)
7. Top Performing Schools (By Passing Rate)
8. Math Scores by Grade
9. Reading Scores by Grade
10. Scores by School Spending
11. Scores by School Size
12. Scores by School type
13. Conclusion

<h3><u>Introduction</u></h3>

As a first task, you've been asked to analyze the district-wide standardized test results. You'll be given access to every student's math and reading scores, as well as various information on the schools they attend. Your responsibility is to aggregate the data to and showcase obvious trends in school performance. 

Your final report should include each of the following:

**District Summary**

* Create a high level snapshot (in table form) of the district's key metrics, including:
  * Total Schools
  * Total Students
  * Total Budget
  * Average Math Score
  * Average Reading Score
  * % Passing Math
  * % Passing Reading
  * Overall Passing Rate (Average of the above two)

**School Summary**

* Create an overview table that summarizes key metrics about each school, including:
  * School Name
  * School Type
  * Total Students
  * Total School Budget
  * Per School Budget
  * Average Math Score
  * Average Reading Score
  * % Passing Math
  * % Passing Reading
  * Overall Passing Rate (Average of the above two)

**Top Performing Schools (By Passing Rate)**

* Create a table that highlights the top 5 performing schools based on Overall Passing Rate. Include:
  * School Name
  * School Type
  * Total Students
  * Total School Budget
  * Per School Budget
  * Average Math Score
  * Average Reading Score
  * % Passing Math
  * % Passing Reading
  * Overall Passing Rate (Average of the above two)

**Top Performing Schools (By Passing Rate)**

* Create a table that highlights the bottom 5 performing schools based on Overall Passing Rate. Include all of the same metrics as above.

**Math Scores by Grade**

* Create a table that lists the average Math Score for students of each grade level (9th, 10th, 11th, 12th) at each school.

**Reading Scores by Grade**

* Create a table that lists the average Reading Score for students of each grade level (9th, 10th, 11th, 12th) at each school.

**Scores by School Spending**

* Create a table that breaks down school performances based on average Spending Ranges (Per Student). Use 4 reasonable bins to group school spending. Include in the table each of the following:
  * Average Math Score
  * Average Reading Score
  * % Passing Math
  * % Passing Reading
  * Overall Passing Rate (Average of the above two)

**Scores by School Size**

* Repeat the above breakdown, but this time group schools based on a reasonable approximation of school size (Small, Medium, Large).

**Scores by School Type**

* Repeat the above breakdown, but this time group schools based on school type (Charter vs. District).

As final considerations:

* Your script must work for both data-sets given.
* You must use the Pandas Library and the Jupyter Notebook.
* You must submit a link to your Jupyter Notebook with the viewable Data Frames. 
* You must include an exported markdown version of your Notebook called  `README.md` in your GitHub repository.  
* You must include a written description of three observable trends based on the data.

<p></p>

<p></p>

<h3><u>Import libraries</u></h3>

In [12]:
#import libraries for analysis
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

<p></p>

<p></p>

In [13]:
#import csv files for analysis
df_schools = pd.read_csv('raw_data/schools_complete.csv')
df_students = pd.read_csv('raw_data/students_complete.csv')


#rename columns from name to school
df_schools.rename_axis({'name':'school'},axis=1,inplace=True)
df_school_summary = df_schools.copy()

<p></p>

<p></p>

<h3><u>District Summary</u></h3>

In [14]:
#Generated df_school_district to only look at district schools
df_school_district = df_schools[df_schools['type'] == 'District']


#total number of schools in the District 
total_school_district = df_school_district.shape[0]


#Total number of student in the district
total_number_students_district = df_school_district['size'].sum()


#Total Budget of District
total_school_budget_district = df_school_district['budget'].sum()


#merge df_school_district and df_students 
df_schools_student_district_merge = df_school_district.merge(df_students,how='outer',on='school')


#deleted columns budget and size
del df_schools_student_district_merge['budget']
del df_schools_student_district_merge['size']


#total average reading and math scores for the district
total_avg_reading_scores_district = df_schools_student_district_merge.groupby(['type'])['reading_score'].mean()[0]
total_avg_math_scores_district = df_schools_student_district_merge.groupby(['type'])['math_score'].mean()[0]


#Students must have a 70% on math or reading to pass 
pass_reading_district = df_schools_student_district_merge[df_schools_student_district_merge['reading_score'] >= 70]
pass_math_district = df_schools_student_district_merge[df_schools_student_district_merge['math_score'] >= 70]


#Count the number of students passing reading or math
passing_reading_count_district = pass_reading_district.groupby(['type'])['Student ID'].count()[0]
passing_math_count_district = pass_math_district.groupby(['type'])['Student ID'].count()[0]


#Calc for average students passing reading or math
avg_passing_math_district = (passing_math_count_district/total_number_students_district)*100
avg_passing_reading_district = (passing_reading_count_district/total_number_students_district)*100


#Calc for overall passing in the district
overall_passing_district = (avg_passing_math_district+avg_passing_reading_district)/2


#Generate dictionary for district summary dataframe
d = {'Total_School': [total_school_district],
     'Total_Students': [total_number_students_district],
     'Total_Budget': [total_school_budget_district],
     'Average_Math_score':[total_avg_math_scores_district],
     'Average_Reading_score':[total_avg_reading_scores_district],
     '%Passing Math': [avg_passing_math_district],
     '%Passing Reading': [avg_passing_reading_district],
     '%Overall Passing Rate': [overall_passing_district]}


#Generated dataframe using above dictionary
district_summary = pd.DataFrame(d)


#Arrange columns
district_summary = district_summary[['Total_School',
                                     'Total_Students',
                                     'Total_Budget',
                                     'Average_Math_score',
                                     'Average_Reading_score',
                                     '%Passing Math',
                                     '%Passing Reading',
                                     '%Overall Passing Rate' ]]


#Display dataframe for district summary
district_summary

,Total_School,Total_Students,Total_Budget,Average_Math_score,Average_Reading_score,%Passing Math,%Passing Reading,%Overall Passing Rate
0,7,26976,17347923,76.987026,80.962485,66.518387,80.905249,73.711818

<p></p>

<p></p>

<h3><u>School Summary</u></h3>

In [15]:
#deleted column School ID
del df_school_summary['School ID']


#Calc the series for Per Student Budget
df_school_summary['Per Student Budget'] = df_school_summary['budget']/df_school_summary['size']


#Using groupy found the average reading and math scores for each school
avg_passing_math_reading_table = df_students.groupby(['school'])['reading_score','math_score'].mean().reset_index()


#merge average passing math and reading to school summary dataframe
df_school_summary = df_school_summary.merge(avg_passing_math_reading_table,on='school',how='outer')


#Students must have a 70% on math or reading to pass 
summary_criteria_passing_reading = df_students[df_students['reading_score'] >= 70]
summary_criteria_passing_math = df_students[df_students['math_score'] >= 70]


#Count the number of students passing reading and rename column
passing_reading_count_summary =summary_criteria_passing_reading.groupby(['school'])['reading_score'].count().reset_index()
passing_reading_count_summary.rename_axis({'reading_score':'reading_count'},axis=1,inplace=True)


#Count the number of students passing math and rename column
passing_math_count_summary = summary_criteria_passing_math.groupby(['school'])['math_score'].count().reset_index()
passing_math_count_summary.rename_axis({'math_score':'math_count'},axis=1,inplace=True)


#merge over count to passing math dataframe
passing_count = passing_math_count_summary.merge(passing_reading_count_summary,on='school',how='inner')


#merge overall passing count to school summary dataframe
df_school_summary = df_school_summary.merge(passing_count,on='school',how='outer')


#Calc for % Passing math and reading 
df_school_summary['% Passing Math'] = (df_school_summary['math_count']/df_school_summary['size'])*100
df_school_summary['% Passing Reading'] = (df_school_summary['reading_count']/df_school_summary['size'])*100


#delete math and reading count from dataframe
del df_school_summary['math_count']
del df_school_summary['reading_count']


#Calc for % Overall Passing series in school summary dataframe
df_school_summary['% Overall Passing'] = (df_school_summary['% Passing Math'] + df_school_summary['% Passing Reading'])/2


#rename axis for reading and math scores to average reading and average math scores in school summary dataframe 
df_school_summary.rename_axis({'reading_score':'Average Reading Score',
                               'math_score': 'Average Math Score'},axis= 1 , inplace= True)


#apply font to school summary dataframe to highlight certain columns 
cm = sns.light_palette('green',as_cmap=True)


#display school summary dataframe
df_school_summary.style.background_gradient(cmap=cm,subset=['Average Reading Score',
                                                                'Average Math Score',
                                                                '% Passing Math',
                                                                '% Passing Reading',
                                                                '% Overall Passing'])

<p></p>

<p></p>

<h3><u>Top Performing Schools (By Passing Rate)</u></h3>

In [16]:
#Using the school summary dataframe found the Top Perfroming School by % Overall Passing column
df_Top_Performing_Schools_By_Passsing_Rate = df_school_summary.sort_values(by=['% Overall Passing'],ascending=False).head(5)

#Display Top Performing Schools (By Passing Rate)
df_Top_Performing_Schools_By_Passsing_Rate.style.background_gradient(cmap=cm,subset=['% Overall Passing'])

<p></p>

<p></p>

<h3><u>Bottom Performing Schools (By Passing Rate)</u></h3>

In [17]:
#Using the school summary dataframe found the Bottom Perfroming School by % Overall Passing column
df_Bottom_Performing_Schools_By_Passsing_Rate = df_school_summary.sort_values(by=['% Overall Passing']).head(5)

#Display Bottom Performing Schools (By Passing Rate) 
df_Bottom_Performing_Schools_By_Passsing_Rate.style.background_gradient(cmap=cm,subset=['% Overall Passing'])

<p></p>

<p></p>

<h3><u>Math Scores by Grade</u></h3>

In [18]:
#Using a pivot table grouped the math scores by average grade
df_math_scores__grade =pd.pivot_table(df_students,values=['math_score'],index=['school'],columns=['grade'])
df_math_scores__grade = df_math_scores__grade.reindex_axis(labels=['9th',
                                                                   '10th',
                                                                   '11th',
                                                                   '12th'],axis=1,level=1)
#Display Math Scores by Grade
df_math_scores__grade.style.background_gradient(cmap=cm)

<p></p>

<p></p>

<h3><u>Reading Scores by Grade</u></h3>

In [19]:
#Using a pivot table grouped the reading scores by average grade
df_reading_scores__grade=pd.pivot_table(df_students,values=['reading_score'],index=['school'],columns=['grade'])


#reindex axis for reading scores by grade dataframe
df_reading_scores__grade = df_reading_scores__grade.reindex_axis(labels=['9th',
                                                                         '10th',
                                                                         '11th',
                                                                         '12th'],axis=1,level=1)
#Display Reading Scores by Grade
df_reading_scores__grade.style.background_gradient(cmap= cm)

<p></p>

<p></p>

<h3><u>Scores by School Spending</u></h3>

In [20]:
#Copy school summary dataframe to new dataframe titled scores by school spending
scores_by_school_spending = df_school_summary.copy()

#assigned labels for bins
label_spending = np.array(['577.99 to 591.50', '591.51 to 628.00', '628.01 to 641.50', '641.51 to 655.00'])

#bin Per Student Budget column
scores_by_school_spending['Per Student Budget'] = pd.qcut(scores_by_school_spending['Per Student Budget'],4,labels=label_spending,precision=0)

#Display scores by school spending 
scores_by_school_spending.groupby(['Per Student Budget'])['Average Reading Score', 
                                                          'Average Math Score',
                                                          '% Passing Math',
                                                          '% Passing Reading',
                                                          '% Overall Passing'].mean().style.background_gradient(cmap= cm)

<p></p>

<p></p>

<h3><u>Scores by School Size</u></h3>

In [21]:
#Copy school summary dataframe to new dataframe titled scores by school size
scores_by_school_size = df_school_summary.copy()


#label small, medium, and large for bins
label = np.array(['small','medium','large'])


#bin school size 
scores_by_school_size['size'] = pd.qcut(scores_by_school_size['size'],3,labels=label)

#Use groupby to find the average scores for reading, math, % Passing Math, % Passing Reading, and % Overall Passing 
scores_by_school_size = scores_by_school_size.groupby(['size'])['Average Reading Score',
                                                                'Average Math Score', 
                                                                '% Passing Math',
                                                                '% Passing Reading',
                                                                '% Overall Passing'].mean().reset_index()

#reindex axis for dataframe 
scores_by_school_size = scores_by_school_size.reindex_axis(labels=[2,1,0])
scores_by_school_size.set_index(keys=['size'],inplace=True)

#Display scores by school size dataframe
scores_by_school_size.style.background_gradient(cmap= cm)

<p></p>

<p></p>

<h3><u>Scores by School Type</u></h3>

In [22]:
#Copy school summary dataframe to new dataframe titled scores by school type
scores_by_school_type = df_school_summary.copy()


#Use groupby to find the average scores for reading, math, % Passing Math, % Passing Reading, and % Overall Passing 
scores_by_school_type = scores_by_school_type.groupby(['type'])['Average Reading Score',
                                                                'Average Math Score',
                                                                '% Passing Math',
                                                                '% Passing Reading',
                                                                '% Overall Passing'].mean().reset_index()
#Set index to type
scores_by_school_type.set_index('type',inplace=True)

#Display scores by school type dataframe
scores_by_school_type.style.background_gradient(cmap=cm)

<h3><u>Conclusion</u></h3>
<ul>
<li>The overall passing scores appear to be directly related to the type of school. The average overall passing scores are higher for charter schools than district schools.</li> 
<p></p>
<li>In the Scores by School Spending table, there is a relationship between the per student budget and overall passing scores. As the per student budget increased, the overall passing scores decreased.</li>
<p></p>
<li>In the Scores by School Size table, there is a relationship with  math, reading, and overall passing scores by size.As the school student size increased the scores dropped. </li>
</ul>